name: workout
description: Run a workout session on Wear OS and Tizen. Get data such as heart rate in real time.
version: 0.4.0
homepage: https://github.com/Rexios80/flutter_workout

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_plugin_android_lifecycle: ^2.0.5
  permission_handler: ^9.0.1
  permission_handler_tizen: ^1.0.0

dev_dependencies:
  rexios_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.rexios.workout
        pluginClass: WorkoutPlugin
      tizen:
        pluginClass: WorkoutPlugin
        fileName: workout_plugin.h
