name: workout_example
description: Demonstrates how to use the workout plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_sensors: ^1.0.1
  firebase_messaging: ^7.0.3

  http: ^0.13.4


dev_dependencies:
  rexios_lints: ^1.0.0